name = "ML_as_MO"
uuid = "871ff0e3-44a5-4569-9f8c-43c8af2866ab"
authors = ["Joonatan Linkola", "Eetu Reijonen", "Nikita Belyak", "Fabricio Oliveira"]
version = "1.0.0-DEV"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
